### ISSUE TITLE
Join/Leave, Start/Stop, Death, and Advancement messages.

### ISSUE THREAD

**Issue by tobfos2611** [MaFeLP/MCDC#41]
This is a really good plugin for my server, as it doesn't rely on webhooks like others do, so it works well with my Matrix bridge. It would be completely usable if Join/Leave, Start/Stop, Death, and Advancement messages where also sent to discord.

**Comment by MaFeLP** [comment]
This has been implemented and tested in [v0.12.1-beta](https://github.com/MaFeLP/MCDC/releases/tag/v0.12.1-beta)
